import { test, expect } from "@playwright/test";
import { mockWorklens, mockExistingConversation } from "./fixture.js";

test("sidebar and usage info use shared hints while the usage entry stays quiet", async ({ page }) => {
  await mockExistingConversation(page);
  await page.goto("/");
  const hint = page.locator('[data-slot="tooltip-content"]');
  const toggle = page.locator(".sidebar-toggle");
  await toggle.hover();
  await expect(hint).toHaveText("Collapse sidebar");
  await expect(toggle).not.toHaveAttribute("title");
  await toggle.click();
  await expect(toggle).toHaveAttribute("aria-expanded", "false");
  await page.mouse.move(0, 0);
  await page.keyboard.press("Tab");
  await page.keyboard.press("Shift+Tab");
  await expect(toggle).toBeFocused();
  await expect(hint).toHaveCount(1);
  await expect(hint).toHaveText("Expand sidebar");
  await page.keyboard.press("Escape");
  await expect(hint).toBeHidden();
  const usage = page.locator(".usage-trigger");
  await usage.hover();
  await expect(hint).toBeHidden();
  await expect(usage.locator('[data-slot="usage-icon"]')).toBeVisible();
  await expect(page.locator(".usage-popover")).toHaveCount(0);
  await expect(usage).not.toHaveAttribute("title");
  await usage.click();
  await expect(page.locator(".usage-popover")).toBeVisible();
  await usage.hover();
  await expect(hint).toBeHidden();
  await expect(page.locator(".usage-popover [title]")).toHaveCount(0);
  await page.locator(".usage-model").hover();
  await expect(hint).toBeHidden();
  await page.getByRole("tab", { name: "Details", exact: true }).click();
  await page.locator(".usage-total strong").hover();
  await expect(hint).toBeHidden();
  const info = page.getByRole("button", { name: "About total usage" });
  await info.hover();
  await expect(hint).toContainText("All retained local sessions");
  await page.mouse.move(0, 0);
  await info.focus();
  await page.keyboard.press("Shift+Tab");
  await page.keyboard.press("Tab");
  await expect(info).toBeFocused();
  await expect(hint).toContainText("All retained local sessions");
  await page.keyboard.press("Escape");
});

test("header details return for history and disappear on new chat", async ({ page }) => {
  await mockExistingConversation(page);
  await page.goto("/");
  await expect(page.locator('[data-slot="chat-title"]')).toHaveText("Existing conversation");
  await expect(page.locator(".usage-trigger")).toBeVisible();
  await page.getByRole("button", { name: /New chat/ }).click();
  await expect(page.locator('[data-slot="chat-title"]')).toHaveCount(0);
  await expect(page.locator(".usage-trigger")).toHaveCount(0);
  await page.getByRole("button", { name: "Existing conversation", exact: true }).click();
  await expect(page.locator(".usage-trigger")).toBeVisible();
  await page.getByRole("button", { name: "Settings", exact: true }).click();
  await expect(page.getByRole("heading", { name: "About", exact: true })).toHaveCount(0);
});
